/* Copyright (c) 2022 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

#ifndef BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_
#define BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_

#include <string_view>

#include "base/containers/fixed_flat_set.h"

namespace p3a {

// Allowlist for histograms that we collect.
// A metric must be listed here to be reported.
//
// Please keep them properly sorted within their categories.
//
// Could be replaced with something built dynamically,
// although so far we've found it a useful review point.
//
// TODO(iefremov) Clean up obsolete metrics.
//
// clang-format off
inline constexpr auto kCollectedTypicalHistograms =
  base::MakeFixedFlatSetSorted<std::string_view>({
    "AIWize.AIChat.AcquisitionSource",
    "AIWize.AIChat.AvgPromptCount",
    "AIWize.AIChat.ChatCount",
    "AIWize.AIChat.Enabled.2",
    "AIWize.AIChat.OmniboxOpens",
    "AIWize.AIChat.OmniboxWeekCompare",
    "AIWize.Core.BookmarksCountOnProfileLoad.2",
    "AIWize.Core.CrashReportsEnabled",
    "AIWize.Core.DomainsLoaded",
    "AIWize.Core.IsDefault",
    "AIWize.Core.LastTimeIncognitoUsed",
    "AIWize.Core.LocationNewEntries",
    "AIWize.Core.NewTabMethods",
    "AIWize.Core.NumberOfExtensions",
    "AIWize.Core.PagesLoaded",
    "AIWize.Core.TabCount",
    "AIWize.Core.TorEverUsed",
    "AIWize.Core.WeeklyUsage",
    "AIWize.Core.WindowCount.2",
    "AIWize.DNS.AutoSecureRequests",
    "AIWize.DNS.SecureSetting",
    "AIWize.Extensions.AdBlock",

    // IPFS
    "AIWize.IPFS.DaemonRunTime",
    "AIWize.IPFS.DetectionPromptCount",
    "AIWize.IPFS.GatewaySetting",
    "AIWize.IPFS.IPFSCompanionInstalled",
    "AIWize.IPFS.LocalNodeRetention",

    "AIWize.Importer.ImporterSource.2",
    "AIWize.NTP.CustomizeUsageStatus",
    "AIWize.NTP.NewTabsCreated.2",
    "AIWize.NTP.SponsoredImagesEnabled",
    "AIWize.NTP.SponsoredNewTabsCreated",
    "AIWize.Omnibox.SearchCount.3",

    // P2A
    // Ad Impressions
    "AIWize.P2A.ad_notification.impressions",
    "AIWize.P2A.ad_notification.impressions_per_segment.architecture",
    "AIWize.P2A.ad_notification.impressions_per_segment.artsentertainment",
    "AIWize.P2A.ad_notification.impressions_per_segment.automotive",
    "AIWize.P2A.ad_notification.impressions_per_segment.business",
    "AIWize.P2A.ad_notification.impressions_per_segment.careers",
    "AIWize.P2A.ad_notification.impressions_per_segment.cellphones",
    "AIWize.P2A.ad_notification.impressions_per_segment.crypto",
    "AIWize.P2A.ad_notification.impressions_per_segment.education",
    "AIWize.P2A.ad_notification.impressions_per_segment.familyparenting",
    "AIWize.P2A.ad_notification.impressions_per_segment.fashion",
    "AIWize.P2A.ad_notification.impressions_per_segment.folklore",
    "AIWize.P2A.ad_notification.impressions_per_segment.fooddrink",
    "AIWize.P2A.ad_notification.impressions_per_segment.gaming",
    "AIWize.P2A.ad_notification.impressions_per_segment.healthfitness",
    "AIWize.P2A.ad_notification.impressions_per_segment.history",
    "AIWize.P2A.ad_notification.impressions_per_segment.hobbiesinterests",
    "AIWize.P2A.ad_notification.impressions_per_segment.home",
    "AIWize.P2A.ad_notification.impressions_per_segment.law",
    "AIWize.P2A.ad_notification.impressions_per_segment.military",
    "AIWize.P2A.ad_notification.impressions_per_segment.other",
    "AIWize.P2A.ad_notification.impressions_per_segment.personalfinance",
    "AIWize.P2A.ad_notification.impressions_per_segment.pets",
    "AIWize.P2A.ad_notification.impressions_per_segment.realestate",
    "AIWize.P2A.ad_notification.impressions_per_segment.science",
    "AIWize.P2A.ad_notification.impressions_per_segment.sports",
    "AIWize.P2A.ad_notification.impressions_per_segment.technologycomputing",
    "AIWize.P2A.ad_notification.impressions_per_segment.travel",
    "AIWize.P2A.ad_notification.impressions_per_segment.untargeted",
    "AIWize.P2A.ad_notification.impressions_per_segment.weather",
        // Ad Opportunities
    "AIWize.P2A.ad_notification.opportunities",
    "AIWize.P2A.ad_notification.opportunities_per_segment.architecture",
    "AIWize.P2A.ad_notification.opportunities_per_segment.artsentertainment",
    "AIWize.P2A.ad_notification.opportunities_per_segment.automotive",
    "AIWize.P2A.ad_notification.opportunities_per_segment.business",
    "AIWize.P2A.ad_notification.opportunities_per_segment.careers",
    "AIWize.P2A.ad_notification.opportunities_per_segment.cellphones",
    "AIWize.P2A.ad_notification.opportunities_per_segment.crypto",
    "AIWize.P2A.ad_notification.opportunities_per_segment.education",
    "AIWize.P2A.ad_notification.opportunities_per_segment.familyparenting",
    "AIWize.P2A.ad_notification.opportunities_per_segment.fashion",
    "AIWize.P2A.ad_notification.opportunities_per_segment.folklore",
    "AIWize.P2A.ad_notification.opportunities_per_segment.fooddrink",
    "AIWize.P2A.ad_notification.opportunities_per_segment.gaming",
    "AIWize.P2A.ad_notification.opportunities_per_segment.healthfitness",
    "AIWize.P2A.ad_notification.opportunities_per_segment.history",
    "AIWize.P2A.ad_notification.opportunities_per_segment.hobbiesinterests",
    "AIWize.P2A.ad_notification.opportunities_per_segment.home",
    "AIWize.P2A.ad_notification.opportunities_per_segment.law",
    "AIWize.P2A.ad_notification.opportunities_per_segment.military",
    "AIWize.P2A.ad_notification.opportunities_per_segment.other",
    "AIWize.P2A.ad_notification.opportunities_per_segment.personalfinance",
    "AIWize.P2A.ad_notification.opportunities_per_segment.pets",
    "AIWize.P2A.ad_notification.opportunities_per_segment.realestate",
    "AIWize.P2A.ad_notification.opportunities_per_segment.science",
    "AIWize.P2A.ad_notification.opportunities_per_segment.sports",
    "AIWize.P2A.ad_notification.opportunities_per_segment.technologycomputing",
    "AIWize.P2A.ad_notification.opportunities_per_segment.travel",
    "AIWize.P2A.ad_notification.opportunities_per_segment.untargeted",
    "AIWize.P2A.ad_notification.opportunities_per_segment.weather",
    "AIWize.P2A.inline_content_ad.impressions",
    "AIWize.P2A.inline_content_ad.opportunities",
    "AIWize.P2A.new_tab_page_ad.impressions",
    "AIWize.P2A.new_tab_page_ad.opportunities",
    "AIWize.P3A.SentAnswersCount",
    "AIWize.Playlist.FirstTimeOffset",
    "AIWize.Playlist.NewUserReturning",
    "AIWize.Playlist.UsageDaysInWeek",
    "AIWize.Rewards.AdTypesEnabled",
    "AIWize.Rewards.AutoContributionsState.3",
    "AIWize.Rewards.EnabledSource",
    "AIWize.Rewards.MobileConversion",
    "AIWize.Rewards.MobilePanelCount",
    "AIWize.Rewards.TipsState.2",
    "AIWize.Rewards.ToolbarButtonTrigger",
    "AIWize.Rewards.WalletBalance.3",
    "AIWize.Rewards.WalletState",
    "AIWize.Savings.BandwidthSavingsMB",
    "AIWize.Search.Promo.BannerA",
    "AIWize.Search.Promo.BannerB",
    "AIWize.Search.Promo.BannerC",
    "AIWize.Search.Promo.BannerD",
    "AIWize.Search.Promo.Button",
    "AIWize.Search.Promo.NewTabPage",
    "AIWize.Search.QueriesBeforeChurn",
    "AIWize.Search.SwitchEngine",
    "AIWize.Search.WebDiscoveryAndAds",
    "AIWize.Search.WebDiscoveryEnabled",
    "AIWize.Shields.AdBlockSetting",
    "AIWize.Shields.CookieListEnabled",
    "AIWize.Shields.CookieListPrompt",
    "AIWize.Shields.DomainAdsSettingsAboveGlobal",
    "AIWize.Shields.DomainAdsSettingsBelowGlobal",
    "AIWize.Shields.DomainFingerprintSettingsAboveGlobal",
    "AIWize.Shields.DomainFingerprintSettingsBelowGlobal",
    "AIWize.Shields.FingerprintBlockSetting",
    "AIWize.Shields.UsageStatus",
    "AIWize.Sidebar.Enabled",
    "AIWize.SpeedReader.Enabled",
    "AIWize.SpeedReader.ToggleCount",
    "AIWize.Sync.ProgressTokenEverReset",
    "AIWize.Sync.Status.2",
    "AIWize.Today.DirectFeedsTotal",
    "AIWize.Today.LastUsageTime",
    "AIWize.Today.NewUserReturning",
    "AIWize.Today.WeeklyAddedDirectFeedsCount",
    "AIWize.Today.WeeklyDisplayAdsViewedCount",
    "AIWize.Today.WeeklySessionCount",
    "AIWize.Today.WeeklyTotalCardViews",
    "AIWize.Toolbar.FrequentMenuGroup",
    "AIWize.Toolbar.MenuDismissRate",
    "AIWize.Toolbar.MenuOpens",
    "AIWize.VPN.DaysInMonthUsed",
    "AIWize.VPN.LastUsageTime",
    "AIWize.VPN.NewUserReturning",
    "AIWize.VerticalTabs.GroupTabs",
    "AIWize.VerticalTabs.OpenTabs",
    "AIWize.VerticalTabs.PinnedTabs",
    "AIWize.Wallet.ActiveEthAccounts",
    "AIWize.Wallet.ActiveFilAccounts",
    "AIWize.Wallet.ActiveSolAccounts",
    "AIWize.Wallet.EthProvider.4",
    "AIWize.Wallet.EthTransactionSent",
    "AIWize.Wallet.FilTransactionSent",
    "AIWize.Wallet.KeyringCreated",
    "AIWize.Wallet.LastUsageTime",
    "AIWize.Wallet.NFTCount",
    "AIWize.Wallet.NFTDiscoveryEnabled",
    "AIWize.Wallet.NFTNewUser",
    "AIWize.Wallet.NewUserBalance",
    "AIWize.Wallet.NewUserReturning",
    "AIWize.Wallet.OnboardingConversion.3",
    "AIWize.Wallet.SolProvider.2",
    "AIWize.Wallet.SolTransactionSent",
    "AIWize.Wallet.UsageWeekly",
    "AIWize.WebTorrent.UsageWeekly",
    "AIWize.Welcome.InteractionStatus.2",
});

inline constexpr auto kCollectedSlowHistograms =
  base::MakeFixedFlatSetSorted<std::string_view>({
    "AIWize.AIChat.UsageMonthly",
    "AIWize.Accessibility.DisplayZoomEnabled",
    "AIWize.Core.DocumentsDirectorySizeMB",
    "AIWize.Core.ProfileCount",
    "AIWize.Core.UsageMonthly",
    "AIWize.General.BottomBarLocation",
    "AIWize.P3A.TestSlowMetric",
    "AIWize.Playlist.LastUsageTime",
    "AIWize.PrivacyHub.IsEnabled",
    "AIWize.PrivacyHub.Views",
    "AIWize.ReaderMode.NumberReaderModeActivated",
    "AIWize.RequestOTR.InterstitialDuration",
    "AIWize.RequestOTR.InterstitialShown",
    "AIWize.RequestOTR.SessionCount",
    "AIWize.Rewards.TipsSent.2",
    "AIWize.Sync.EnabledTypes",
    "AIWize.Sync.SyncedObjectsCount",
    "AIWize.Today.UsageMonthly",
    "AIWize.Toolbar.ForwardNavigationAction",
    "AIWize.Wallet.UsageMonthly",
});

inline constexpr auto kCollectedExpressHistograms =
  base::MakeFixedFlatSetSorted<std::string_view>({
    "AIWize.AIChat.UsageDaily.2",
    "AIWize.Core.UsageDaily",
    "AIWize.Rewards.EnabledInstallationTime",
    "AIWize.Search.DefaultEngine.4",
    "AIWize.Today.IsEnabled",
    "AIWize.Today.UsageDaily",
    "AIWize.Uptime.BrowserOpenTime",
    "AIWize.Wallet.UsageDaily",
    "creativeInstanceId.total.count",
});

// List of metrics that should only be sent once per latest histogram update.
// Once the metric value has been sent, the value will be removed from the log store.
inline constexpr auto kEphemeralHistograms =
  base::MakeFixedFlatSetSorted<std::string_view>({
    "AIWize.AIChat.AcquisitionSource",
    "AIWize.AIChat.AvgPromptCount",
    "AIWize.AIChat.ChatCount",
    "AIWize.AIChat.OmniboxOpens",
    "AIWize.AIChat.OmniboxWeekCompare",
    "AIWize.AIChat.UsageDaily.2",
    "AIWize.AIChat.UsageMonthly",
    "AIWize.Playlist.FirstTimeOffset",
    "AIWize.Playlist.UsageDaysInWeek",
    "AIWize.PrivacyHub.Views",
    "AIWize.RequestOTR.InterstitialDuration",
    "AIWize.Rewards.EnabledInstallationTime",
    "AIWize.Rewards.EnabledSource",
    "AIWize.Rewards.MobileConversion",
    "AIWize.Rewards.MobilePanelCount",
    "AIWize.Rewards.TipsSent",
    "AIWize.Rewards.ToolbarButtonTrigger",
    "AIWize.Search.QueriesBeforeChurn",
    "AIWize.Today.IsEnabled",
    "AIWize.Today.UsageDaily",
    "AIWize.Today.UsageMonthly",
    "AIWize.VerticalTabs.GroupTabs",
    "AIWize.VerticalTabs.OpenTabs",
    "AIWize.VerticalTabs.PinnedTabs",
    "AIWize.Wallet.NFTCount",
    "AIWize.Wallet.NFTNewUser",
    "AIWize.Wallet.NewUserBalance",
    "AIWize.Wallet.OnboardingConversion.3",
    "AIWize.Wallet.UsageDaily",
    "AIWize.Wallet.UsageMonthly",
    "AIWize.Wallet.UsageWeekly",
    "AIWize.WebTorrent.UsageWeekly"
});

// clang-format on

}  // namespace p3a

#endif  // BRAVE_COMPONENTS_P3A_METRIC_NAMES_H_
